# Generated by Django 3.2.3 on 2021-06-01 11:13

import uuid

from django.db import migrations

import common.models
import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxesPolicyRange',
            fields=[
                ('id', common.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', common.models.DateTimeField(auto_now_add=True)),
                ('updated_at', common.models.DateTimeField(auto_now=True)),
                ('amount_from', common.models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('_amount_to', common.models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('percent', common.models.PositiveIntegerField(default=0, validators=[common.validators.MaxValueValidator(limit_value=100)])),
            ],
            options={
                'db_table': 'taxes_policy_range',
            },
        ),
        migrations.CreateModel(
            name='TaxesPolicy',
            fields=[
                ('id', common.models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', common.models.DateTimeField(auto_now_add=True)),
                ('updated_at', common.models.DateTimeField(auto_now=True)),
                ('year', common.models.PositiveIntegerField(unique=True)),
                ('ranges', common.models.ManyToManyField(related_name='taxes_policies', to='taxes_policy.TaxesPolicyRange')),
            ],
            options={
                'verbose_name_plural': 'Taxes policies',
                'db_table': 'taxes_policy',
            },
        ),
    ]
