version: '3.3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/
    ports:
      - 8008:8000
    environment:
      - ALLOWED_HOSTS=["*"]
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE=postgres
      - URL_PREFIX=api/v1/
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./taxes_calculator_prot_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=taxes_calculator_db
volumes:
  taxes_calculator_prot_pg_data:
    external: true
